### ISSUE TITLE
计组第二章异或描述错误

### ISSUE THREAD

**Issue by zhrloveball** [ddy-ddy/cs-408#16]
<img width="1237" alt="image" src="https://github.com/ddy-ddy/cs-408/assets/23250761/e61f1cd7-681d-4300-a4a2-266c544e0be0">

原文是“两个值相同就为1”，应该是“同为0，异为1”

**Comment by ddy-ddy** [comment]
你是对滴，这里是我写错了。正确写法如下：
【逻辑异或XOR】同为0，异为1
