### ISSUE TITLE
计组第三章SSD描述错误

### ISSUE THREAD

**Issue by zhrloveball** [ddy-ddy/cs-408#17]
<img width="641" alt="image" src="https://github.com/ddy-ddy/cs-408/assets/23250761/1fa121b7-dd42-41eb-a53f-fef128805e68">

Flash 存储器(Flash Memory)才是闪存，SSD 是基于闪存的硬盘

**Comment by ddy-ddy** [comment]
你是对滴。这里我写错了。
正确的描述为：
1、Flash 存储器(Flash Memory)是闪存
2、SSD 是基于闪存的硬盘
