### ISSUE TITLE
计组第三章字扩展法有误

### ISSUE THREAD

**Issue by zhrloveball** [ddy-ddy/cs-408#18]
<img width="1082" alt="image" src="https://github.com/ddy-ddy/cs-408/assets/23250761/60d349cd-642c-481a-8d61-40a152730b6c">

8k*8的存储器，存储字数8k=2^13，需要13根地址线，图上A0~A12一共13根没啥问题吧

**Comment by ddy-ddy** [comment]
你是对的，这里应该是我之前计算错了存储字数
