### ISSUE TITLE
计网第五章传输层 传输层的寻址和端口 端口号长度能标识的不同端口号数量有误？

### ISSUE THREAD

**Issue by hellocaoyi** [ddy-ddy/cs-408#19]
如题，端口号长度16bit，应能标识65536个不同的端口号
![WX20230722-170010@2x](https://github.com/ddy-ddy/cs-408/assets/52915409/c5540e66-56e3-40cb-b969-cec324e25c5b)

**Comment by ddy-ddy** [comment]
这里我应该是打错了，你的回答是正确滴。
2的16次方=65536，即能标识65536个不同的端口号。
