### ISSUE TITLE
请问：“无符号数：寄存器位数”是什么意思？

### ISSUE THREAD

**Issue by scbzfarmingtest** [ddy-ddy/cs-408#2]
计组第二章第一列无符号数
![image](https://user-images.githubusercontent.com/68948943/190112559-82dfb5b9-d7fb-4f22-8ae5-1e98edeeb57c.png)
请问这里寄存器位数是指？比如8个寄存器，3位无符号数来指代（类似内存地址）？

**Comment by ddy-ddy** [comment]
> 计组第二章第一列无符号数
> 
> ![image](https://user-images.githubusercontent.com/68948943/190112559-82dfb5b9-d7fb-4f22-8ae5-1e98edeeb57c.png)
> 
> 请问这里寄存器位数是指？比如8个寄存器，3位无符号数来指代（类似内存地址）？

这里应该指的是：寄存器的位数反映了无符号数的表示范围，如8位寄存器，其无符号数表示范围为0-256。
这个笔记做的比较简略，之后会考虑可读性加上一些解释说明。

**Comment by ddy-ddy** [comment]
> 计组第二章第一列无符号数
> 
> ![image](https://user-images.githubusercontent.com/68948943/190112559-82dfb5b9-d7fb-4f22-8ae5-1e98edeeb57c.png)
> 
> 请问这里寄存器位数是指？比如8个寄存器，3位无符号数来指代（类似内存地址）？

寄存器的位数也叫机器字长。比如一个32位地址寄存器MAR，那他可以表示的地址范围就是0-2^32-1，而这个范围就是32位无符号数表示的范围。

**Comment by scbzfarmingtest** [comment]
谢谢！

**Comment by scbzfarmingtest** [comment]
谢谢
抱歉再问一个。请问”寄存器的位数也叫机器字长“这句话是对的吗？
因为王道有这个题：
![image](https://user-images.githubusercontent.com/68948943/190119532-049e0fbe-9ca3-47e3-9d6c-e35473ef0549.png)
尽管后面也有说：
![image](https://user-images.githubusercontent.com/68948943/190119733-312d004d-e88a-4278-a389-b39300c46f44.png)
所以不选是因为不是定义尽管选项说法没错？还是并不完全对？比如16位机器是不是可以拥有32位寄存器？

**Comment by scbzfarmingtest** [comment]
抱歉没有自我判断能力，但是这有篇文章。[内部寄存器、外设寄存器和内存的区别](https://blog.csdn.net/Michael177/article/details/121322258)。
是不是应该说：”cpu内部的寄存器位数就是机器字长“，单说”寄存器“未必正确？

**Comment by ddy-ddy** [comment]
> 谢谢
> 
> 抱歉再问一个。请问”寄存器的位数也叫机器字长“这句话是对的吗？
> 
> 因为王道有这个题：
> 
> ![image](https://user-images.githubusercontent.com/68948943/190119532-049e0fbe-9ca3-47e3-9d6c-e35473ef0549.png)
> 
> 尽管后面也有说：
> 
> ![image](https://user-images.githubusercontent.com/68948943/190119733-312d004d-e88a-4278-a389-b39300c46f44.png)
> 
> 所以不选是因为不是定义尽管选项说法没错？还是并不完全对？比如16位机器是不是可以拥有32位寄存器？

不好意思，这句话我的表述有点问题。准确的说法应该是：“一般情况下可通过寄存器的位数判断机器字长”。机器字长就是计算机一次能处理的二进制数长度。
至于你说的“16位机器是否可以拥有32位寄存器”。按我的理解应该是不能的，就好比64位计算机可以用64位的操作系统，也可以用32位的操作系统。但是32位计算机只能同32位的os，不能用64位的os。不过我也不清楚我的说法是不是正确。

**Comment by ddy-ddy** [comment]
> 抱歉没有自我判断能力，但是这有篇文章。[内部寄存器、外设寄存器和内存的区别](https://blog.csdn.net/Michael177/article/details/121322258)。
> 
> 是不是应该说：”cpu内部的寄存器位数就是机器字长“，单说”寄存器“未必正确？

可以参考下这篇博客
http://t.csdn.cn/VwtWs

**Comment by scbzfarmingtest** [comment]
好的谢谢！我又看了下，似乎关键在于**整数运算**和**通用寄存器**一般等于机器字长。比如浮点数会更多。[比如](https://www.cnblogs.com/goalpower/p/4032559.html#:~:text=%E5%AE%9E%E9%99%85%E4%B8%8A%EF%BC%8CX86%E7%9A%84FPU%E4%B8%AD%E5%8C%85%E5%90%AB%E4%B8%80%E4%B8%AA%E6%B5%AE%E7%82%B9%E5%AF%84%E5%AD%98%E5%99%A8%E6%A0%88%EF%BC%8C%E5%AE%83%E5%8C%85%E5%90%AB%E4%BA%868%E4%B8%AA80%E4%BD%8D%E7%9A%84%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E8%A1%8C%E6%B5%AE%E7%82%B9%E8%BF%90%E7%AE%97%E7%9A%84%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%8C%E6%B5%AE%E7%82%B9%E6%95%B0%E4%BB%A5%E5%8F%8C%E7%B2%BE%E5%BA%A6%E6%A0%BC%E5%BC%8F%E5%AD%98%E5%82%A8%E5%9C%A8%E8%BF%99%E4%BA%9B%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%AD%EF%BC%8C%E6%97%A0%E8%AE%BA,%E6%98%AF%E5%8D%95%E7%B2%BE%E5%BA%A6%E3%80%81%E5%8F%8C%E7%B2%BE%E5%BA%A6%E8%BF%98%E6%98%AF%E6%95%B4%E6%95%B0%E7%AD%89%EF%BC%8C%E8%A2%ABload%E5%88%B0%E8%BF%99%E4%BA%9B%E4%B8%AA%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%AD%E5%90%8E%EF%BC%8C%E9%83%BD%E4%BC%9A%E8%BD%AC%E5%8C%96%E4%B8%BA%E5%8F%8C%E7%B2%BE%E5%BA%A6%E3%80%82)这里说x86有8个80位浮点寄存器。

**Comment by ddy-ddy** [comment]
> 好的谢谢！我又看了下，似乎关键在于**整数运算**和**通用寄存器**一般等于机器字长。比如浮点数会更多。[比如](https://www.cnblogs.com/goalpower/p/4032559.html#:~:text=%E5%AE%9E%E9%99%85%E4%B8%8A%EF%BC%8CX86%E7%9A%84FPU%E4%B8%AD%E5%8C%85%E5%90%AB%E4%B8%80%E4%B8%AA%E6%B5%AE%E7%82%B9%E5%AF%84%E5%AD%98%E5%99%A8%E6%A0%88%EF%BC%8C%E5%AE%83%E5%8C%85%E5%90%AB%E4%BA%868%E4%B8%AA80%E4%BD%8D%E7%9A%84%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E8%A1%8C%E6%B5%AE%E7%82%B9%E8%BF%90%E7%AE%97%E7%9A%84%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%8C%E6%B5%AE%E7%82%B9%E6%95%B0%E4%BB%A5%E5%8F%8C%E7%B2%BE%E5%BA%A6%E6%A0%BC%E5%BC%8F%E5%AD%98%E5%82%A8%E5%9C%A8%E8%BF%99%E4%BA%9B%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%AD%EF%BC%8C%E6%97%A0%E8%AE%BA,%E6%98%AF%E5%8D%95%E7%B2%BE%E5%BA%A6%E3%80%81%E5%8F%8C%E7%B2%BE%E5%BA%A6%E8%BF%98%E6%98%AF%E6%95%B4%E6%95%B0%E7%AD%89%EF%BC%8C%E8%A2%ABload%E5%88%B0%E8%BF%99%E4%BA%9B%E4%B8%AA%E5%AF%84%E5%AD%98%E5%99%A8%E4%B8%AD%E5%90%8E%EF%BC%8C%E9%83%BD%E4%BC%9A%E8%BD%AC%E5%8C%96%E4%B8%BA%E5%8F%8C%E7%B2%BE%E5%BA%A6%E3%80%82)这里说x86有8个80位浮点寄存器。

对的，我觉得这个理解是透彻且正确的。👍

**Comment by scbzfarmingtest** [comment]
刚才看2020年好像考了机器字长，所以又详细查了下：
[不同架构下，ALU可以属于寄存器，也可以不含寄存器（此时叫做虚拟寄存器）](https://www.zhihu.com/question/410083278)
![image](https://user-images.githubusercontent.com/68948943/190887593-547de295-6b09-477c-930c-446f530b558b.png)
[ALU的输入是机器字长（也是内部数据总线的根数）](https://blog.csdn.net/qq_34756106/article/details/103524082)
![image](https://user-images.githubusercontent.com/68948943/190887645-7d833897-1302-4a11-81bd-3f71ba016421.png)
除了通用寄存器和整数计算的寄存器(如果ALU是寄存器，显然包含在内)，其他的位数一般都等于机器字长。[见：寄存器的分类](https://www.eefocus.com/baike/502591#:~:text=%E5%AF%84%E5%AD%98%E5%99%A8%E5%8F%AF%E5%88%86%E4%B8%BA%E4%BB%A5%E4%B8%8B%E5%87%A0%E7%B1%BB%EF%BC%9A%201%E3%80%81%20%E9%80%9A%E7%94%A8%E5%AF%84%E5%AD%98%E5%99%A8,%E7%BB%84%20%E9%80%9A%E7%94%A8%E5%AF%84%E5%AD%98%E5%99%A8%E7%BB%84%E5%8C%85%E6%8B%ACAX%E3%80%81BX%E3%80%81CX%E3%80%81DX4%E4%B8%AA16%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%8C%E7%94%A8%E4%BB%A5%E5%AD%98%E6%94%BE16%E4%BD%8D%E6%95%B0%E6%8D%AE%E6%88%96%E5%9C%B0%E5%9D%80%E3%80%82%20%E4%B9%9F%E5%8F%AF%E7%94%A8%E4%BD%9C8%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%E3%80%82%20%E7%94%A8%E4%BD%9C8%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%E6%97%B6%E5%88%86%E5%88%AB%E8%AE%B0%E4%B8%BAAH%E3%80%81AL%E3%80%81BH%E3%80%81BL%E3%80%81CH%E3%80%81CL%E3%80%81DH%E3%80%81DL%E3%80%82)

主要的判定办法好像就是寄存器的作用。比如整数加减运算一定是一个周期完成的，而浮点数（对阶、求和、规格化、舍入、溢出判断）显然不是一个周期。指令寄存器、段寄存器，从指令系统可以知道也不一定是一个周期完成。指针和变址寄存器、标志寄存器等作用和数据总线不接边，而且甚至有些可以用通用寄存器（不一定是32位的E,X还是H），所以也不一定等于机器字长

**Comment by ddy-ddy** [comment]
> 刚才看2020年好像考了机器字长，所以又详细查了下：
> 
> [不同架构下，ALU可以属于寄存器，也可以不含寄存器（此时叫做虚拟寄存器）](https://www.zhihu.com/question/410083278)
> 
> ![image](https://user-images.githubusercontent.com/68948943/190887593-547de295-6b09-477c-930c-446f530b558b.png)
> 
> [ALU的输入是机器字长（也是内部数据总线的根数）](https://blog.csdn.net/qq_34756106/article/details/103524082)
> 
> ![image](https://user-images.githubusercontent.com/68948943/190887645-7d833897-1302-4a11-81bd-3f71ba016421.png)
> 
> 除了通用寄存器和整数计算的寄存器(如果ALU是寄存器，显然包含在内)，其他的位数一般都等于机器字长。[见：寄存器的分类](https://www.eefocus.com/baike/502591#:~:text=%E5%AF%84%E5%AD%98%E5%99%A8%E5%8F%AF%E5%88%86%E4%B8%BA%E4%BB%A5%E4%B8%8B%E5%87%A0%E7%B1%BB%EF%BC%9A%201%E3%80%81%20%E9%80%9A%E7%94%A8%E5%AF%84%E5%AD%98%E5%99%A8,%E7%BB%84%20%E9%80%9A%E7%94%A8%E5%AF%84%E5%AD%98%E5%99%A8%E7%BB%84%E5%8C%85%E6%8B%ACAX%E3%80%81BX%E3%80%81CX%E3%80%81DX4%E4%B8%AA16%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%EF%BC%8C%E7%94%A8%E4%BB%A5%E5%AD%98%E6%94%BE16%E4%BD%8D%E6%95%B0%E6%8D%AE%E6%88%96%E5%9C%B0%E5%9D%80%E3%80%82%20%E4%B9%9F%E5%8F%AF%E7%94%A8%E4%BD%9C8%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%E3%80%82%20%E7%94%A8%E4%BD%9C8%E4%BD%8D%E5%AF%84%E5%AD%98%E5%99%A8%E6%97%B6%E5%88%86%E5%88%AB%E8%AE%B0%E4%B8%BAAH%E3%80%81AL%E3%80%81BH%E3%80%81BL%E3%80%81CH%E3%80%81CL%E3%80%81DH%E3%80%81DL%E3%80%82)
> 
> 
> 
> 主要的判定办法好像就是寄存器的作用。比如整数加减运算一定是一个周期完成的，而浮点数（对阶、求和、规格化、舍入、溢出判断）显然不是一个周期。指令寄存器、段寄存器，从指令系统可以知道也不一定是一个周期完成。指针和变址寄存器、标志寄存器等作用和数据总线不接边，而且甚至有些可以用通用寄存器（不一定是32位的E,X还是H），所以也不一定等于机器字长

说的很详细也易懂！感谢分享！
