### ISSUE TITLE
刊误

### ISSUE THREAD

**Issue by marvell-D** [ddy-ddy/cs-408#21]
你好,在数据结构的总结,第八章排序算法部分,关于快速排序的总结中
![IMG_0167](https://github.com/ddy-ddy/cs-408/assets/68533005/bc1f8dc5-464a-42cc-be1b-d095592172b4)
最小递归深度=log2n
最大递归深度=n
这里是不是写反了
一处出现在第八章开头的总结表格上
一处出现在快排的内容表格中
PS:感谢总结,二轮用来回忆非常受用

**Comment by ddy-ddy** [comment]
你是对的，这里我写反了。
正确的是：
最小递归深度=log2n
最大递归深度=n
