### ISSUE TITLE
数据结构出栈操作有误

### ISSUE THREAD

**Issue by Ron-zs** [ddy-ddy/cs-408#23]
![image](https://github.com/ddy-ddy/cs-408/assets/56159465/c4d63f60-2de8-426e-8216-e564d668828d)

**Comment by Ron-zs** [comment]
应写为x=S.data[S.top--]
PS：感谢博主付出

**Comment by ddy-ddy** [comment]
你是对滴，这里优点问题。
正确的是：
1.把出栈的数据赋值给x：x = S.data[S.top--]
2.返回x值：return x
