### ISSUE TITLE
笔记改进

### ISSUE THREAD

**Issue by yyfisyyds** [ddy-ddy/cs-408#25]
作者耗费很大的精力创作了本笔记，真的是一件令人佩服的事情，我针对笔记右做了补充，加入了王道系列课程的所有知识，整理的组成原理笔记在小红薯开源，昵称为：认真工作的崽崽，请大家前来白嫖，真诚希望大家可以凭借我们的笔记一战上岸

**Comment by ddy-ddy** [comment]
可以可以
