### ISSUE TITLE
兄弟，有人拿你的408笔记在小红书引流啊，把你的笔记直接当成自己的笔记在那发，我说叫他备注一下来源还把我拉黑了，主页链接在正文

### ISSUE THREAD

**Issue by DD123456D** [ddy-ddy/cs-408#27]
那个人的主页链接
https://www.xiaohongshu.com/user/profile/5ef4bbd3000000000101c863?xhsshare=CopyLink&appuid=63f84206000000001001f432&apptime=1696074818

**Comment by systemoutprintlnhelloworld** [comment]
他408区所有帖子我已经骂了一遍了，他发的第一条帖子那个pdf跟大大的计网文件名连结束时间都一模一样，抄袭无疑了。号子应该会被封几天，同志们加油

**Comment by ddy-ddy** [comment]
他之前有联系过我，我看了他的帖子，一方面有加入他自己的内容，一方面也有制作成pdf方便打印。我有让他加上github来源，后面的事情我就没怎么看了😂
反正我笔记开源的嘛，大家都可以拿去二创之类的，只要不骗人就行。

**Comment by SC-persistence** [comment]
卖的太贵了，而且我觉得这个行为本身就是一种欺骗行为
