### ISSUE TITLE
计组第五章有关MAR的位数

### ISSUE THREAD

**Issue by Similarityoung** [ddy-ddy/cs-408#29]
![image](https://github.com/ddy-ddy/cs-408/assets/94664304/d4ed35a5-0996-4f56-a1e9-33217c5d85e0)MAR是存储单元的个数，这里的指令字长请问怎么理解

**Comment by Similarityoung** [comment]
![IMG_0697](https://github.com/ddy-ddy/cs-408/assets/94664304/c395f55f-e07a-470d-8db0-a4525619acc3)
这里写后读和读后写的英文缩写好像反了

**Comment by ddy-ddy** [comment]
你是对的，正确的内容应该是：
1、先写后读，对应英文为RAW
2、先读后写，对应英文为WAR

**Comment by ddy-ddy** [comment]
> ![image](https://user-images.githubusercontent.com/94664304/272851225-d4ed35a5-0996-4f56-a1e9-33217c5d85e0.png)MAR是存储单元的个数，这里的指令字长请问怎么理解

1、指令字长指一个指令字中包含的二进制代码的位数
2、指令字长取决于【操作码的长度】【操作数地址】【操作数地址的个数】
