### ISSUE TITLE
计组第五章MDR的位数取决于存储字长吧好像

### ISSUE THREAD

**Issue by Similarityoung** [ddy-ddy/cs-408#30]
![image](https://github.com/ddy-ddy/cs-408/assets/94664304/adb4650e-8b8e-4989-840a-a29a4d76503b)我在做2021年真题的时候发现，这里计算机字长16位，cpu与主存的系统总线的数据线是8位，所以MDR是8位而不是16位。

**Comment by ddy-ddy** [comment]
你是对的，通常情况下，MDR的位数=系统总线的数据线位数，所以MDR是8位。
