### ISSUE TITLE
操作系统第二章中的线程部分的“关于线程可共享的东西”的第3点错误

### ISSUE THREAD

**Issue by YanShourui** [ddy-ddy/cs-408#34]
线 程程之间不能共享虚拟地址空间，线程之间不能共享栈指针
应改为
进 程之间不能共享虚拟地址空间，线程之间不能共享栈指针

**Comment by ddy-ddy** [comment]
你是对滴。
线程之间可以共享虚拟地址空间，但不能共享栈指针。
进程之间不能直接共享虚拟地址空间，但可以通过IPC机制进行数据交换和共享。
