### ISSUE TITLE
 博主考哪个学校了，笔记真棒

### ISSUE THREAD

**Issue by GENARDING** [ddy-ddy/cs-408#36]

**Comment by ddy-ddy** [comment]
工作了嘞

**Comment by yyqEternal** [comment]
> 工作了嘞

博主考了一次失败直接放弃了吗？查多少分上岸

**Comment by ddy-ddy** [comment]
是滴，报的中科大软院，目标太高没上岸😭

**Comment by yyqEternal** [comment]
> 卧槽大佬科软，我学历带专太差了只能考研提升学历不然一直是外包，大佬当初考研差-多少上分，我也想上985，我的985梦

**Comment by yyqEternal** [comment]
> 是滴，报的中科大软院，目标太高没上岸😭

卧槽大佬科软，我学历带专太差了只能考研提升学历不然一直是外包，大佬当初考研差-多少上分，我也想上985，我的985梦😭

**Comment by ddy-ddy** [comment]
差了十多分，科软太难考了，全是大牛😭。加油，你肯定能考上的！

**Comment by yyqEternal** [comment]
> 差了十多分，科软太难考了，全是大牛😭。加油，你肯定能考上的！

哥你太强了360的分数线你还差十多分就上了，我都不敢想我能考这么多，我能鼓起勇气考完就算成功😭，我现在说要考科软都是装的等我填志愿的时候我就不敢了

**Comment by ddy-ddy** [comment]
没事加油，一步一个脚印总能行的！
