### ISSUE TITLE
有么有兴趣整理个类似政治背诵手册的背诵知识点嘞

### ISSUE THREAD

**Issue by renming-lab** [ddy-ddy/cs-408#5]

**Comment by ddy-ddy** [comment]
其实我的onenote笔记就有点类似于背诵手册了，笔记排版都是按照王道书的来的，主要是精简了王道书的一些概念，加入自己的理解，加入例题，并配上手绘的图等。原本书上几十页的知识点，在笔记里面用几个表格就可以概括了。

如果要做成那种能打印出来的知识点的话，我感觉比较难。主要是排版的问题，笔记里面很多表格图表，有很长的也有很宽的。

如果你有兴趣的话也可以拿这个笔记进行再次创作或者排版。ヾ(◍°∇°◍)ﾉﾞ
